const STATUS_LOGIN = 1
const STATUS_SIGNUP = 2
const STATUS_DIVINA_MANJU = 3
const STATUS_DIVINA_AVALO = 4
const STATUS_FONTPAGE = 5
const STATUS_ADMIN = 6
const STATUS_RESULT = 7
const STATUS_HISTORY = 8
const STATUS_DAILY = 9
const STATUS_PROFILE = 10
const STATUS_ENCYCLOPEDIA = 11
const STATUS_DAILY_RESULT = 12
const STATUS_ADMIN_PANEL = 13
const STATUS_POEM_MANAGER = 14
const STATUS_ARTICLE_MANAGER = 15
const STATUS_STATISTICS = 16
const STATUS_POEM_EDITOR = 17
const STATUS_NOTE_EDITOR = 18
const STATUS_FORGOT_PASSWORD = 19  // ← 加這個
const STATUS_ARTICLE_LIST = 20;  // 文章列表頁
const STATUS_ARTICLE_DETAIL = 21;  // 文章詳情頁
const STATUS_ARTICLE_CREATE = 22;  // 發布文章頁
const STATUS_ARTICLE_EDIT = 23;  // 編輯文章頁

const CONST = {
  STATUS_LOGIN,
  STATUS_SIGNUP,
  STATUS_DIVINA_MANJU,
  STATUS_DIVINA_AVALO,
  STATUS_FONTPAGE,
  STATUS_ADMIN,
  STATUS_RESULT,
  STATUS_HISTORY,
  STATUS_DAILY,
  STATUS_PROFILE,
  STATUS_ENCYCLOPEDIA,
  STATUS_DAILY_RESULT,
  STATUS_ADMIN_PANEL,
  STATUS_POEM_MANAGER,
  STATUS_ARTICLE_MANAGER,
  STATUS_STATISTICS,
  STATUS_POEM_EDITOR,
  STATUS_NOTE_EDITOR,
  STATUS_FORGOT_PASSWORD,  // ← 加這個
 STATUS_ARTICLE_LIST ,  // 文章列表頁
 STATUS_ARTICLE_DETAIL,   // 文章詳情頁
 STATUS_ARTICLE_CREATE ,  // 發布文章頁
 STATUS_ARTICLE_EDIT ,
}

export { CONST }